### ISSUE TITLE
Rails.application.secrets is deprecated from rails 7.2.0

### ISSUE THREAD

**Issue by eddiecheung-shopify** [Shopify/ejson-rails#71]
### Description

From `rails` `7.2.0`, the `Rails.application.secrets` is deprecated. However, the current version of `ejson-rails` is still referencing to `Rails.application.secrets` in [here](https://github.com/Shopify/ejson-rails/blob/f2da168c8ef3c0a1bdf05ffe2ae15d991f3240d5/lib/ejson/rails/railtie.rb#L18).

For those Ruby application using `ejson-rails` gem, we need to wait for the newer version of `ejson-rails` gem that is compatible to `rails` `7.2.0` in order to upgrade this repo to use.

**Comment by etiennebarrie** [comment]
Before 1.0.0, you can use `gem "ejson-rails", require: "ejson/rails/skip_secrets"` to be compatible with 7.2.0. 
1.0.0 doesn't write to Rails secrets anymore and is compatible with 7.2.0. It was just released https://rubygems.org/gems/ejson-rails/versions/1.0.0
